Update ffmpeg.py
Fixing the audio reader error.
```
  File "avp/toolkit/ffmpeg.py", line 453, in readAudioFile
    audio_array = numpy.fromstring(raw_audio, dtype="int16")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: The binary mode of fromstring is removed, use frombuffer instead
```